# dexart flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs flow

# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs flow

# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs flow


# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs flow

# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs flow

# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs flow


# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs flow

# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs flow

# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs flow
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs flow




# dexart dynamo 512 dim
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_512_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs dynamo


# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_512_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs dynamo


# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_512_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs dynamo





# dexart dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_toilet/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_toilet --seed 360 --object_obs dynamo


# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_laptop/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_laptop --seed 360 --object_obs dynamo


# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs dynamo

# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 0 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 1 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 10 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 128 --object_obs dynamo
# python imitate_dexart.py --ckpt_dir ./model/dexart_bucket/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dexart_bucket --seed 360 --object_obs dynamo





# dapg flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 360 --object_obs flow


# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_pen/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 360 --object_obs flow


# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 360 --object_obs flow


# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 360 --object_obs flow

# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 0 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 1 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 10 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 128 --object_obs flow
# python imitate_dapg.py --ckpt_dir ./model/dapg_door/flow_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 360 --object_obs flow



# dapg dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 0 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 1 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 10 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 128 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 360 --object_obs dynamo

# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 0 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 1 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 10 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 128 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 360 --object_obs dynamo

# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 0 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 1 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 10 --object_obs dynamo
# python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_relocate/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_relocate --seed 360 --object_obs dynamo


python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 360 --object_obs dynamo

python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 360 --object_obs dynamo

python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_pen/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_pen --seed 360 --object_obs dynamo


python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 360 --object_obs dynamo

python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 360 --object_obs dynamo

python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_hammer/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_hammer --seed 360 --object_obs dynamo


python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_10_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_10_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_10_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_10_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_10_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 10 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 360 --object_obs dynamo

python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_20_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_20_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_20_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_20_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_20_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 20 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 360 --object_obs dynamo

python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_40_seed_0 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 0 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_40_seed_1 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 1 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_40_seed_10 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 10 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_40_seed_128 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 128 --object_obs dynamo
python imitate_dapg.py --ckpt_dir ./model/dapg_door/dynamo_128_chuck_40_seed_360 --policy_class ACT --kl_weight 10 --chunk_size 40 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 --num_epochs 2000  --lr 1e-5 --task_name dapg_door --seed 360 --object_obs dynamo